### PR TITLE
Adding Team-work contract

### PR DESCRIPTION
**Pull request by kmoravej**

### CODE REVIEW

**Comment by kmoravej** [comment]
#1

**Comment by kmoravej** [comment]
I am not sure if it is OK to put the contract in our repo or not. In dsci_522 and 532, we did include the team contract in the repo.

**Review by sukh2929 — COMMENTED** [review]
This looks really good!! I think Tiff mentioned in the milestone1.md that we should not have it in our public repos. So, maybe we can have a google doc for this.

**Comment by sukh2929** [comment]
closing because we are not going to put this on version control.

**Pull request closed without merging**
